# Copyright (C) 2026 Nobleo Autonomous Solutions B.V.

[workspace]
preview = ["pixi-build"]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
  "robostack-kilted",
]
platforms = ["linux-64", "linux-aarch64"]

[package]
name = "generate_parameter_library_example"

[package.build.source]
git = "https://github.com/PickNikRobotics/generate_parameter_library.git"
tag = "0.7.0"
subdirectory = "example"

[package.build.backend]
name = "pixi-build-ros"
version = "*"
